### ISSUE TITLE
Download only PowerShell specific CheatSheets code fix

### ISSUE THREAD

**Issue by martin77s** [PrateekKumarSingh/CheatSheets#1]
The **Download only PowerShell specific CheatSheets** code should include **?raw=true** at the end of the url. otherwise it downloads the webrequest response and not the real file.
So the onliner should be:
(iwr "https://github.com/PrateekKumarSingh/CheatSheets").Links | ?{$_.title -Like "*Powershell*"} | %{iwr "http://github.com$($_.href)?raw=true" -OutFile $_.title -Verbose}

**Comment by PrateekKumarSingh** [comment]
Thanks for the heads up!
